config/urls.py

from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from django.conf import settings

from django.conf.urls.static import static
# from django.views.generic import TemplateView

# index_View= TemplateView.as_view(template_name="index.html")


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.IMAGES_URL, document_root=settings.IMAGES_ROOT)

myapp/urls.py
from django.urls import path
from . import tests
from . import views
from .views import LikeBase1,LikeBase2,LikeBase3,LikeBase4
from .views import Like1,Like2,Like3,Like4
from .views import search
app_name = 'myapp'
urlpatterns = [
path('', tests.test, name='test'),


path('register/', views.AccountRegistration.as_view(), name='register'),
path('login/', views.Login,name='Login'),
path('logout/', views.Logout, name='Logout'),


path('top/', views.top, name='top'),

path('post/', views.View_post.as_view(), name='post'),
path('post1/', views.View_post1.as_view(), name='post1'),
path('post2/', views.View_post2.as_view(), name='post2'),
path('post3/', views.View_post3.as_view(), name='post3'),
path('post4/', views.View_post4.as_view(), name='post4'),


path('chapter1/', views.View_chapter1, name='chapter1'),
path('chapter2/', views.View_chapter2, name='chapter2'),
path('chapter3/', views.View_chapter3, name='chapter3'),
path('chapter4/', views.View_chapter4, name='chapter4'),


path('result1/',views.View_result1.as_view(),name="result1"),
path('result2/',views.View_result2.as_view(),name="result2"),
path('result3/',views.View_result3.as_view(),name="result3"),
path('result4/',views.View_result4.as_view(),name="result4"),


path('profile/', views.View_profile.as_view(), name='profile'),

path('like_result1/', views.likeresult1.as_view(), name='like_result1'),
path('like_result2/', views.likeresult2.as_view(), name='like_result2'),
path('like_result3/', views.likeresult3.as_view(), name='like_result3'),
path('like_result4/', views.likeresult4.as_view(), name='like_result4'),

path('like1/<int:pk>',Like1.as_view(), name='like1'),
path('like2/<int:pk>',Like2.as_view(), name='like2'),
path('like3/<int:pk>',Like3.as_view(), name='like3'),
path('like4/<int:pk>',Like4.as_view(), name='like4'),


path('search/',search, name='search'),
    

]

templates/chapter1.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">

  <head>

    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1">



    <title>Lostbelt No.1</title>

    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/slick.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/slide.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'slick/slick.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{%static 'slick/slick-theme.css' %}"/>

  </head>
  <body>
    <header>

      <nav class="top_nav">
        <ul>
          <figure class="icon"><img src="{% static 'imges/icon_1.png' %}" alt="ロゴ画像"></figure>
          <li><a href= "{% url 'myapp:top' %}">Top</a></li>

          <li class="has-child"><a href="#">TimeLine</a>
            <ul>
            <li><a href="{% url 'myapp:chapter1' %}">Lostbelt No.1</a></li>
            <li><a href="{% url 'myapp:chapter2' %}">Lostbelt No.2</a></li>
            <li><a href="{% url 'myapp:chapter3' %}">Lostbelt No.3</a></li>
            <li><a href="{% url 'myapp:chapter4' %}">Lostbelt No.4</a></li>

          </ul>
          <li><a href="{% url 'myapp:post' %}">Post</a></li>
        <li><a href="{% url 'myapp:search' %}">Search</a></li>
          <li><a href="{% url 'myapp:profile' %}">Profile</a></li>
          <li><a href="{% url 'myapp:Logout' %}">Logout</a></li>
          </li>
          </ul>
        </nav>
      </div>
        </header>
        
      <h1>2部1章</h1>
      <div id="top_img">
        <ul class="slider">
          <li><img src="{% static 'imges/slide_1_1.png' %}" alt="1章"></li>
          <li><img src="{% static 'imges/slide_1_2.png' %}" alt="1章"></li>
          <li><img src="{% static 'imges/slide_1_3.png' %}" alt="1章"></li>
          <li><img src="{% static 'imges/slide_1_4.png' %}" alt="1章"></li>
        </ul>
        </div>
      <main class="tl_main">        


      

      <div class="concept">
        <p class="title">
          永久凍土帝国アナスタシア <br>[獣国の皇女]</p>
          <p>その日、未来は跡形もなく片付けられた。</p>
          <p>ソラからの侵略の手で人類史は白紙に戻った。</p>
          <p> 我々の功績は不正解だったと断定され、汎人類史は過去にすら計上</p>
          <p>されず、天文台は凍結し、世界は七つの異聞に分断された。</p>
          <p>そして―――</p>
        <p> 三ヶ月の沈黙を破って、虚数の海から最後の人類が浮上する。</p>
          <p>彼らが挑むは極寒の歴史に閉ざされた新世界。</p>
          <p>2018年4月。</p>
          <p>いま、全てを取り戻す戦いが始まる。</p>
      </div>


</div>

{% for obj in object_list %}

<div class="TL_post">
  <div class="tl_user">
    <img src="{% static 'imges/icon_3.png' %}">
    <p> {{obj.user}} </p>
  </div>

  <div class="tl_img">
  <figure>
    <img src="/{{ obj.post_img }}" alt="投稿画像">
  </figure>
  </div>
  <div class="tl_btn">

 

    {% if request.user in obj.like1.all %}
    <a href="{% url 'myapp:like1' obj.pk %}" tabindex="-1"  aria-disabled="true"><img  src="{% static 'imges/hart2.png' %}" type=value  alt="ハート">     </a>{{obj.like1.count}}
    {% else %}
    <a href="{% url 'myapp:like1' obj.pk %}" tabindex="-1"  aria-disabled="true"> <img  src="{% static 'imges/hart.png' %}" type=value  alt="ハート"></a>{{obj.like1.count}}
    {% endif %} 
    </div>
    <div class="tl_txt">
    <p> {{obj.post_txt}} </p> 
  </div>
</div>
{%endfor%}




      </main>
    <a class="pagetop" href="#"><div class="pagetop_arrow"></div></a>


    <footer>
      <nav>
        <ul>
          <li><a href="{% url 'myapp:top' %}">Top</a></li>
          <li><a href="{% url 'myapp:post' %}">Post</a></li>
        <li><a href="{% url 'myapp:search' %}">Search</a></li>
          <li><a href="{% url 'myapp:profile' %}">Profile</a></li>
          <li><a href="{% url 'myapp:Logout' %}">Logout</a></li>
        </ul>
        <p>2023 &copy; Copyright Hiramastu Takumi All rights reserved</p>
      </nav> 
    </footer>
  

    <script type="text/javascript" src="//code.jquery.com/jquery-3.4.1.min.js"></script>
    <script type="text/javascript" src="{% static 'slick/slick.min.js' %}"></script>
    <script src="{% static 'js/nav.js' %}"></script> 
    <script src="{% static 'js/slide.js' %}"></script>


  </script>

  </body>

</html>


templates/chapter2.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">

  <head>

    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1">



    <title>Lostbelt No.1</title>

    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/slick.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/slide.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'slick/slick.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{%static 'slick/slick-theme.css' %}"/>

  </head>
  <body>
    <header>

      <nav class="top_nav">
        <ul>
          <figure class="icon"><img src="{% static 'imges/icon_1.png' %}" alt="ロゴ画像"></figure>
          <li><a href= "{% url 'myapp:top' %}">Top</a></li>

          <li class="has-child"><a href="#">TimeLine</a>
            <ul>
            <li><a href="{% url 'myapp:chapter1' %}">Lostbelt No.1</a></li>
            <li><a href="{% url 'myapp:chapter2' %}">Lostbelt No.2</a></li>
            <li><a href="{% url 'myapp:chapter3' %}">Lostbelt No.3</a></li>
            <li><a href="{% url 'myapp:chapter4' %}">Lostbelt No.4</a></li>

          </ul>
          <li><a href="{% url 'myapp:post' %}">Post</a></li>
        <li><a href="{% url 'myapp:search' %}">Search</a></li>
          <li><a href="{% url 'myapp:profile' %}">Profile</a></li>
          <li><a href="{% url 'myapp:Logout' %}">Logout</a></li>
          </li>
          </ul>
        </nav>
      </div>
        </header>
        
      <h1>2部2章</h1>
      <div id="top_img">
        <ul class="slider">
          <li><img src="{% static 'imges/slide_2_1.png' %}" alt="2章"></li>
          <li><img src="{% static 'imges/slide_2_2.png' %}" alt="2章"></li>
          <li><img src="{% static 'imges/slide_2_3.png' %}" alt="2章"></li>
          <li><img src="{% static 'imges/slide_2_4.png' %}" alt="2章"></li>
        </ul>
        </div>
      <main class="tl_main">        


      

        <div class="concept">
          <p class="title">
            無間氷焔世紀 ゲッテルデメルング<br>[ 消えぬ炎の快男児 ]</p>
          <p>魔術世界における三大組織の一つ、</p>
          <p>原初にして最後の“壁”とされる彷徨海バルトアンデルス。</p> 
          <p>文明による魔術の進歩･変化を認めず西暦以前の神秘</p>
          <p>―――神代の魔術のみを絶対原則とし、今の人間社会とは相容れない魔術棟。</p> 
          <p>シャドウ･ボーダーに届いた、送り主不明の通信は、彼の地への座標を指し示す。</p> 
          <p>確証のない不確かな情報を頼りに、彼らは次の目的地として、</p> 
          <p>北海に隠された神代の島を目指すのだが―――</p>
        </p> 
        </div>


    </div>

    {% for obj in object_list %}

    <div class="TL_post">
      <div class="tl_user">
        <img src="{% static 'imges/icon_3.png' %}" alt="アイコン">
        <p> {{obj.user}} </p>
      </div>

      <div class="tl_img">
      {% if obj.post_img %}
        <img src="/{{ obj.post_img }}" alt="投稿画像">
      </div>
      {% endif %} 
      <div class="tl_btn">


        {% if request.user in obj.like2.all %}
        <a href="{% url 'myapp:like2' obj.pk %}" tabindex="-1"  aria-disabled="true"><img  src="{% static 'imges/hart2.png' %}" type=value  alt="ハート">     </a>{{obj.like2.count}}
        {% else %}
        <a href="{% url 'myapp:like2' obj.pk %}" tabindex="-1"  aria-disabled="true"> <img  src="{% static 'imges/hart.png' %}" type=value  alt="ハート"></a>{{obj.like2.count}}
        {% endif %} 
        </div>
        <div class="tl_txt">
        <p> {{obj.post_txt}} </p> 
      </div>
    </div>
    {%endfor%}







      </main>
    <a class="pagetop" href="#"><div class="pagetop_arrow"></div></a>


    <footer>
      <nav>
        <ul>
          <li><a href="{% url 'myapp:top' %}">Top</a></li>
          <li><a href="{% url 'myapp:post' %}">Post</a></li>
        <li><a href="{% url 'myapp:search' %}">Search</a></li>
          <li><a href="{% url 'myapp:profile' %}">Profile</a></li>
          <li><a href="{% url 'myapp:Logout' %}">Logout</a></li>
        </ul>
        <p>2023 &copy; Copyright Hiramastu Takumi All rights reserved</p>
      </nav> 
    </footer>
  

    <script type="text/javascript" src="//code.jquery.com/jquery-3.4.1.min.js"></script>
    <script type="text/javascript" src="{% static 'slick/slick.min.js' %}"></script>
    <script src="{% static 'js/nav.js' %}"></script> 
    <script src="{% static 'js/slide.js' %}"></script>


  </script>

  </body>

</html>

templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">

  <head>

    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1">



    <title>ようこそ！！</title>

    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}">

  </head>
  <body>
    
    <header>
  
    </header>
    <div class="main_bar">
        <figure class="bar_fig">
          <img src="{%static 'imges/bar.jpg' %}" alt="ロゴ">
        </figure>
    </div>


      <div class="start_index"> 
        <h2>ようこそ！！</h2>
        <a href="{% url 'myapp:Login' %}">"ログイン"</a> 
        <a href="{% url 'myapp:register' %}">"新規登録"</a> 
      </div>
 

        
  </body>

</html>

templates/like_result1.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">

  <head>

    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1">



    <title>いいね</title>

    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}">

  </head>
<body>
  <header>

    <nav class="top_nav">
      <ul>
        <figure class="icon"><img src="{% static 'imges/icon_1.png' %}" alt="ロゴ画像"></figure>
        <li><a href= "{% url 'myapp:top' %}">Top</a></li>

        <li class="has-child"><a href="#">TimeLine</a>
          <ul>
          <li><a href="{% url 'myapp:chapter1' %}">Lostbelt No.1</a></li>
          <li><a href="{% url 'myapp:chapter2' %}">Lostbelt No.2</a></li>
          <li><a href="{% url 'myapp:chapter3' %}">Lostbelt No.3</a></li>
          <li><a href="{% url 'myapp:chapter4' %}">Lostbelt No.4</a></li>

        </ul>

        <li><a href="{% url 'myapp:post' %}">Post</a></li>
        <li><a href="{% url 'myapp:search' %}">Search</a></li>
        <li><a href="{% url 'myapp:profile' %}">Profile</a></li>
        <li><a href="{% url 'myapp:Logout' %}">Logout</a></li>
        </li>
        </ul>
      </nav>
    </div>
      </header>
<div class="wrap">

    <h1>投稿完了</h1>

    <main>
      <div id="result">
        
        <p>いいねが押されました</p>

        <div id="result_btn">
          <a href="{% url 'myapp:chapter1' %}">
            <button>戻る</button>
          </a>
        </div>
      </div>
      

    </main>
<a class="pagetop" href="#"><div class="pagetop_arrow"></div></a>

</div>

<footer>
  <nav>
    <ul>
      <li><a href="{% url 'myapp:top' %}">Top</a></li>
      <li><a href="{% url 'myapp:post' %}">Post</a></li>
      <li><a href="{% url 'myapp:search' %}">Search</a></li>
      <li><a href="{% url 'myapp:profile' %}">Profile</a></li>
      <li><a href="{% url 'myapp:Logout' %}">Logout</a></li>
    </ul>
    <p>2023 &copy; Copyright Hiramastu Takumi All rights reserved</p>
  </nav> 
</footer>
    </div>
</body>

</html>

templates/like_result3.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">

  <head>

    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1">



    <title>いいね</title>

    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}">

  </head>
<body>


  <header>

    <nav class="top_nav">
      <ul>
        <figure class="icon"><img src="{% static 'imges/icon_1.png' %}" alt="ロゴ画像"></figure>
        <li><a href= "{% url 'myapp:top' %}">Top</a></li>

        <li class="has-child"><a href="#">TimeLine</a>
          <ul>
          <li><a href="{% url 'myapp:chapter1' %}">Lostbelt No.1</a></li>
          <li><a href="{% url 'myapp:chapter2' %}">Lostbelt No.2</a></li>
          <li><a href="{% url 'myapp:chapter3' %}">Lostbelt No.3</a></li>
          <li><a href="{% url 'myapp:chapter4' %}">Lostbelt No.4</a></li>

        </ul>
        <li><a href="{% url 'myapp:post' %}">Post</a></li>
        <li><a href="{% url 'myapp:search' %}">Search</a></li>
        <li><a href="{% url 'myapp:profile' %}">Profile</a></li>
        <li><a href="{% url 'myapp:Logout' %}">Logout</a></li>
        </li>
        </ul>
      </nav>
    </div>
      </header>
<div class="wrap">

    <h1>投稿完了</h1>

    <main>
      <div id="result">
        
        <p>いいねが押されました</p>

        <div id="result_btn">
          <a href="{% url 'myapp:chapter3' %}">
            <button>戻る</button>
          </a>
        </div>
      </div>
      

    </main>
<a class="pagetop" href="#"><div class="pagetop_arrow"></div></a>

</div>

<footer>
  <nav>
    <ul>
      <li><a href="{% url 'myapp:top' %}">Top</a></li>
      <li><a href="{% url 'myapp:post' %}">Post</a></li>
      <li><a href="{% url 'myapp:search' %}">Search</a></li>
      <li><a href="{% url 'myapp:profile' %}">Profile</a></li>
      <li><a href="{% url 'myapp:Logout' %}">Logout</a></li>
    </ul>
    <p>2023 &copy; Copyright Hiramastu Takumi All rights reserved</p>
  </nav> 
</footer>
    </div>
</body>

</html>

templates/post1.html
{% load static %}
<!DOCTYPE html>

<html lang="ja">
<head>

    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1">



    <title>投稿編集</title>

    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}">

</head>
<body>
    <header>

        <nav class="top_nav">
        <ul>
            <figure class="icon"><img src="{% static 'imges/icon_1.png' %}" alt="ロゴ画像"></figure>
            <li><a href= "{% url 'myapp:top' %}">Top</a></li>

            <li class="has-child"><a href="#">TimeLine</a>
            <ul>
            <li><a href="{% url 'myapp:chapter1' %}">Lostbelt No.1</a></li>
            <li><a href="{% url 'myapp:chapter2' %}">Lostbelt No.2</a></li>
            <li><a href="{% url 'myapp:chapter3' %}">Lostbelt No.3</a></li>
            <li><a href="{% url 'myapp:chapter4' %}">Lostbelt No.4</a></li>

            </ul>
            <li><a href="{% url 'myapp:post' %}">Post</a></li>
            <li><a href="{% url 'myapp:search' %}">Search</a></li>
            <li><a href="{% url 'myapp:profile' %}">Profile</a></li>
            <li><a href="{% url 'myapp:Logout' %}">Logout</a></li>
            </li>
            </ul>
        </nav>
        </div>
        </header>

<div class="wrap">

    <h1>投稿編集</h1>



            <div class="post">
                <form method="POST" class="post-form" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="post1">
                        {{form.post_img}}
                        </div>

                        <div class="post2">
                        {{form.post_txt}}
                        </div>

                        <button type="submit" class=btn >投稿</button>
                </form>
            </div>


</main>
<a class="pagetop" href="#"><div class="pagetop_arrow"></div></a>

</div>

<footer>
    <nav>
    <ul>
        <li><a href="{% url 'myapp:top' %}">Top</a></li>
        <li><a href="{% url 'myapp:post' %}">Post</a></li>
        <li><a href="{% url 'myapp:search' %}">Search</a></li>
        <li><a href="{% url 'myapp:profile' %}">Profile</a></li>
        <li><a href="{% url 'myapp:Logout' %}">Logout</a></li>
    </ul>
    <p>2023 &copy; Copyright Hiramastu Takumi All rights reserved</p>
    </nav> 
</footer>
    </div>
    <script src="{% static 'js/select.js' %}"></script>

</body>


</html>

templates/search.html
<!DOCTYPE html>
{% load static %}
<html lang="ja">

  <head>

    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1">



    <title>Search</title>

    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/slide.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'slick/slick.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{%static 'slick/slick-theme.css' %}"/>

  </head>

  <body>
    <header>

      <nav class="top_nav">
        <ul>
          <figure class="icon"><img src="{% static 'imges/icon_1.png' %}" alt="ロゴ画像"></figure>
          <li><a href= "{% url 'myapp:top' %}">Top</a></li>

          <li class="has-child"><a href="#">TimeLine</a>
            <ul>
            <li><a href="{% url 'myapp:chapter1' %}">Lostbelt No.1</a></li>
            <li><a href="{% url 'myapp:chapter2' %}">Lostbelt No.2</a></li>
            <li><a href="{% url 'myapp:chapter3' %}">Lostbelt No.3</a></li>
            <li><a href="{% url 'myapp:chapter4' %}">Lostbelt No.4</a></li>

          </ul>
          <li><a href="{% url 'myapp:post' %}">Post</a></li>
          <li><a href="{% url 'myapp:search' %}">Search</a></li>
          <li><a href="{% url 'myapp:profile' %}">Profile</a></li>
          <li><a href="{% url 'myapp:Logout' %}">Logout</a></li>
          </li>
          </ul>
        </nav>
      </div>
        </header>
        <h1>検索</h1>
    
        
        

      </div>
      <div id="search">
      <form action='{% url "myapp:search" %}' method="get">
        
          {{ searchForm }}
          <div id="search_sub">      
          <button  type="submit">検索</button>
          <a href='{% url "myapp:search" %}'>クリア</a>
          </div>
      </form>
      </div>



    {% for  obj in articles1 %}

      <div class="tl_search">
        <div class="tl_user">
          <img src="{% static 'imges/icon_3.png' %}">
          <p> {{obj.user}} </p>
        </div>
      
        <div class="tl_img">
        <figure>
          <img src="/{{ obj.post_img }}" alt="投稿画像">
        </figure>
        </div>
        <div class="tl_btn">
    
    
        {% if request.user in obj.like1.all %}
        <a href="{% url 'myapp:like1' obj.pk %}" tabindex="-1"  aria-disabled="true"><img  src="{% static 'imges/hart2.png' %}" type=value  alt="ハート">     </a>{{obj.like1.count}}
        {% else %}
        <a href="{% url 'myapp:like1' obj.pk %}" tabindex="-1"  aria-disabled="true"> <img  src="{% static 'imges/hart.png' %}" type=value  alt="ハート"></a>{{obj.like1.count}}
        {% endif %} 
        </div>
        <div class="tl_txt">
        <p> {{obj.post_txt}} </p> 
      </div>
    </div>
    {%endfor%}
  

    {% for  obj in articles2 %}

      <div class="tl_search">
        <div class="tl_user">
          <img src="{% static 'imges/icon_3.png' %}">
          <p> {{obj.user}} </p>
        </div>
      
        <div class="tl_img">
        <figure>
          <img src="/{{ obj.post_img }}" alt="投稿画像">
        </figure>
        </div>
        <div class="tl_btn">
    
    
        {% if request.user in obj.like2.all %}
        <a href="{% url 'myapp:like2' obj.pk %}" tabindex="-1"  aria-disabled="true"><img  src="{% static 'imges/hart2.png' %}" type=value  alt="ハート">     </a>{{obj.like2.count}}
        {% else %}
        <a href="{% url 'myapp:like2' obj.pk %}" tabindex="-1"  aria-disabled="true"> <img  src="{% static 'imges/hart.png' %}" type=value  alt="ハート"></a>{{obj.like2.count}}
        {% endif %} 
        </div>
        <div class="tl_txt">
        <p> {{obj.post_txt}} </p> 
      </div>
    </div>
    {%endfor%}
    

    {% for  obj in articles3 %}

      <div class="tl_search">
        <div class="tl_user">
          <img src="{% static 'imges/icon_3.png' %}">
          <p> {{obj.user}} </p>
        </div>
      
        <div class="tl_img">
        <figure>
          <img src="/{{ obj.post_img }}" alt="投稿画像">
        </figure>
        </div>
        <div class="tl_btn">
    
    
        {% if request.user in obj.like3.all %}
        <a href="{% url 'myapp:like3' obj.pk %}" tabindex="-1"  aria-disabled="true"><img  src="{% static 'imges/hart2.png' %}" type=value  alt="ハート">     </a>{{obj.like3.count}}
        {% else %}
        <a href="{% url 'myapp:like3' obj.pk %}" tabindex="-1"  aria-disabled="true"> <img  src="{% static 'imges/hart.png' %}" type=value  alt="ハート"></a>{{obj.like3.count}}
        {% endif %} 
        </div>
        <div class="tl_txt">
        <p> {{obj.post_txt}} </p> 
      </div>
    </div>
    {%endfor%}
    

    {% for  obj in articles4 %}

    <div class="tl_search">
      <div class="tl_user">
        <img src="{% static 'imges/icon_3.png' %}">
        <p> {{obj.user}} </p>
      </div>
    
      <div class="tl_img">
      <figure>
        <img src="/{{ obj.post_img }}" alt="投稿画像">
      </figure>
      </div>
      <div class="tl_btn">
  
  
      {% if request.user in obj.like4.all %}
      <a href="{% url 'myapp:like4' obj.pk %}" tabindex="-1"  aria-disabled="true"><img  src="{% static 'imges/hart2.png' %}" type=value  alt="ハート">     </a>{{obj.like4.count}}
      {% else %}
      <a href="{% url 'myapp:like4' obj.pk %}" tabindex="-1"  aria-disabled="true"> <img  src="{% static 'imges/hart.png' %}" type=value  alt="ハート"></a>{{obj.like4.count}}
      {% endif %} 
      </div>
      <div class="tl_txt">
      <p> {{obj.post_txt}} </p> 
    </div>
  </div>
  {%endfor%}
  


</div>
    <a class="pagetop" href="#"><div class="pagetop_arrow"></div></a>

    <footer>
      <nav>
        <ul>
          <li><a href="{% url 'myapp:top' %}">Top</a></li>
        <li><a href="{% url 'myapp:post' %}">Post</a></li>
        <li><a href="{% url 'myapp:search' %}">Search</a></li>
          <li><a href="{% url 'myapp:profile' %}">Profile</a></li>
          <li><a href="{% url 'myapp:Logout' %}">Logout</a></li>
        </ul>
        <p>2023 &copy; Copyright Hiramastu Takumi All rights reserved</p>
      </nav> 
    </footer>


      <script type="text/javascript" src="//code.jquery.com/jquery-3.4.1.min.js"></script>
      <script type="text/javascript" src="{% static 'slick/slick.min.js' %}"></script>
      <script src="{% static 'js/nav.js' %}"></script> 
      <script src="{% static 'js/slide.js' %}"></script>


    </script>

  </body>

</html>